app = "upleveled-final-project-tatli"
primary_region = "otp"

# Apps without volume: Comment out the [mounts] configuration below
[mounts]
  source = "postgres"
  destination = "/postgres-volume"

[env]
  PORT = "8080"
  NEXT_PUBLIC_APOLLO_CLIENT_URI="https://upleveled-final-project-tatli.fly.dev"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
