import './globals.css';
import { ChakraProvider } from '@chakra-ui/react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
// import SmallFooterWithLogoLeft from './components/footer/chackraui/SmallFooterWithLogoLeft';
// import NavWithAction from './components/layout/navheader/chakraui/NavWithAction';
import Navbar from './components/layout/navheader/daisyui/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <ChakraProvider> */}
        {/* <NavWithAction /> */}
        <Navbar />
        <div className=" mx-2 sm:mx-8 lg:mx-24 2xl:mx-40">{children}</div>
        {/* <SmallFooterWithLogoLeft /> */}
        {/* </ChakraProvider> */}
      </body>
    </html>
  );
}
